name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Prueba
      id: prueba
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Prueba
        setup-command: gcc main.c -o main
        command: "./test/test.sh"
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRUEBA_RESULTS: "${{steps.prueba.outputs.result}}"
      with:
        runners: prueba
